[frontends]
    [frontends.nitro-cloud]
    backend = "nitro-cloud"
    passHostHeader = true
    entrypoints = ["http","https"]
        [frontends.nitro-cloud.routes.test_1]
        rule = "Host: cloud.gonitrodev.com"
    [frontends.sso-provider]
    backend = "sso-provider"
    passHostHeader = true
    entrypoints = ["http","https"] # overrides defaultEntryPoints
        [frontends.sso-provider.routes.test_1]
        rule = "Host: sso.gonitrodev.com"
    [frontends.nitroplatform-api]
    backend = "nitroplatform-api"
    passHostHeader = true
    entrypoints = ["http","https"]
        [frontends.nitroplatform-api.routes.test_1]
        rule = "Host: api.nitroplatformdev.com"
    [frontends.document-service-server]
    backend = "document-service-server"
    passHostHeader = true
    entrypoints = ["http","https"]
        [frontends.document-service-server.routes.test_1]
        rule = "Host: dserv.nitroplatformdev.com"
    [frontends.nitrodash]
    backend = "nitrodash"
    passHostHeader = true
    entrypoints = ["http","https"]
        [frontends.nitrodash.routes.test_1]
        rule = "Host: account.nitroplatformdev.com"
